apiVersion: rbac.authorization.k8s.io/v1  
kind: RoleBinding  
metadata:  
  name: {{ include "kube-workflow-restarter.serviceAccountName" . }}
roleRef:  
  apiGroup: rbac.authorization.k8s.io  
  kind: Role  
  name: {{ include "kube-workflow-restarter.serviceAccountName" . }}
subjects:  
  - kind: ServiceAccount  
    name: {{ include "kube-workflow-restarter.serviceAccountName" . }}
