{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-workload-restarter.serviceAccountName" . }}
  labels:
    {{- include "kube-workload-restarter.labels" . | nindent 4 }}
{{- end }}
