name: Package publish
on:
  push:
    branches:
      - 'master'
jobs:
  publish:
      name: Build & Publish
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: 3.8
        
        - name: Install dependencies
          run: pip install -r requirements.txt

        #- name: Build package
        #  run: python -m build
          
        - name: Publish a Python distribution to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}

        - name: Set up Docker
          uses: docker/setup-docker@v1

        - name: Build and publish Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: mydockerhubusername/mydockerimage:latest
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
