name: Publish
on:
  push:
    branches:
      - 'master'
jobs:
  publish:
      name: Build & Publish
      runs-on: ubuntu-latest
      if: ${{ contains(github.event.head_commit.message, '[Releasing]') }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: andreacioni/k8s-workload-restarter:latest,andreacioni/k8s-workload-restarter:0.0.12
          
        
